spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
